### ISSUE TITLE
Modify remote configurations on the fly

### ISSUE THREAD

**Issue by Hackintoshcorp** [crowell/modpagespeed#2093] opened 2022-07-15 15:46 UTC
Hi, how and is it even possible to change the name of the remote configuration file for example by $host variable.

normal config setting:
pagespeed RemoteConfigurationUrl https://example.com/remote.conf;
dynamic config setting:
pagespeed RemoteConfigurationUrl https://$host/remote.conf;

I tried everything but cant get it to work. Do you know how?

**Comment by oschaaf** [comment] 2022-07-15 18:09
Closing as a duplicate of https://github.com/apache/incubator-pagespeed-ngx/issues/1754

**Closed as completed by oschaaf** 2022-07-15 18:09 UTC
